name: deploy.yml
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: 1.92.0
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ID }}
      - run: wrangler build